# Generated by Django 5.2.14 on 2026-05-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Auto-filled from title. Used in URLs.', max_length=220, unique=True)),
                ('description', models.TextField(help_text='Short summary shown on the project card (2–3 sentences).')),
                ('body', models.TextField(blank=True, help_text='Long-form Markdown/plain-text description for a detail page (optional).')),
                ('category', models.CharField(choices=[('Backend', 'Backend Engineering'), ('ML', 'Machine Learning'), ('Fullstack', 'Full Stack')], default='Backend', max_length=20)),
                ('technologies', models.CharField(help_text="Comma-separated list of tech tags, e.g. 'Python, Django, PostgreSQL, REST API'", max_length=500)),
                ('image', models.ImageField(blank=True, help_text='Upload a project screenshot or cover image.', null=True, upload_to='projects/')),
                ('github_link', models.URLField(blank=True, help_text='GitHub repository URL.')),
                ('live_link', models.URLField(blank=True, help_text='Live demo / deployment URL.')),
                ('is_featured', models.BooleanField(default=False, help_text='Pin featured projects to the top of the grid.')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-is_featured', '-date_created'],
            },
        ),
    ]
